export const product = {
  CREATE_PRODUCT: "CREATE_PRODUCT",
  SELECT_PRODUCT: "SELECT_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  ADD_CART: "ADD_CART",
  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT",
  SIGN_UP: "SIGN_UP",
};
